[package]
name = "omama_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
ollama-rs = { version = "0.2.5", features = ["stream"] }
omama_manager = { path = "/run/media/allawiii/projects/zed/Rust/omama_manager/" }
anyhow = "1.0.97"
clap = { version = "4.5.35", features = ["cargo"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.43.0", features = ["full"] }
tokio-stream = "0.1.17"

[profile.release]
panic = "abort"
opt-level = 3
lto = true
